name : CI/CD Pipeline
on : 
  push :
    branches : ["main"]
jobs :
  build :
    runs-on : ubuntu-latest
    steps:
      - name : Checkout the code from repo
        uses : actions/checkout@v2
      - name : Login to Dokcerhub
        uses : docker/login-action@v1
        with :
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name : Bui;d,tag and push the image to dockerhub
        env :
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          IMAGE_NAME: node-image
        run : |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
